/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiemtraoop.De6.Cau2;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import kiemtraoop.De6.Cau1.Word;

/**
 *
 * @author ncv
 */
public class Form extends javax.swing.JFrame {

    ArrayList<Word> ListWord;
    int id=10;

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        ListWord = new ArrayList<Word>();
        ListWord.add(new Word(1, "Hello", "Xin chao"));
        ListWord.add(new Word(2, "Hi", "Xin chao"));
        ListWord.add(new Word(3, "Bye", "Tam biet"));
        ListWord.add(new Word(4, "See", "Nhin"));
        ListWord.add(new Word(5, "Good", "Tot"));
        ListWord.add(new Word(6, "Print", "In"));
        ListWord.add(new Word(7, "One", "1"));
        ListWord.add(new Word(8, "Two", "2"));
        ListWord.add(new Word(9, "Three", "3"));
        ListWord.add(new Word(10, "Four", "4"));
        ListWord.add(new Word(2, "Group", "Nhom"));
        ListWord.add(new Word(2, "OK", "Duoc"));
        sortArray();
    }
    
    public void sortArray(){
        Collections.sort(ListWord, new Comparator<Word>(){
            public int compare (Word w1, Word w2){
                return w1.getEN().compareToIgnoreCase(w2.getEN());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ENTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        VNTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Btn = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TU DIEN");

        ENTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("English");

        VNTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VNTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Vietnamese");

        Btn.setText("Tim Kiem");
        Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActionPerformed(evt);
            }
        });

        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Nhap thong tin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(ENTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(Btn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(message, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ENTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(Btn)
                .addGap(31, 31, 31)
                .addComponent(message)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ENTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ENTxtActionPerformed

    private void VNTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VNTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VNTxtActionPerformed

    private void BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActionPerformed
        // TODO add your handling code here:
        if (Btn.getText().equals("Tim Kiem")) {
            int l = 0, r = ListWord.size() - 1;
            while (l <= r) {
                int m = (l+r) / 2;
                int res = ENTxt.getText().compareToIgnoreCase(ListWord.get(m).getEN());
                System.out.println(res + " " + l + " " + r);
                if (res == 0) {
                    VNTxt.setText(ListWord.get(m).getVN());
                    return;
                }
                if (res > 0)
                    l = m+1;
                else
                    r = m-1;
            }
            VNTxt.setText("");
            message.setText("Khong tim thay tu " + ENTxt.getText() + ". Hay bam nut them de them vao");
            Btn.setText("Them");
            ENTxt.setEnabled(false);
            return;
        }

        if (Btn.getText().equals("Them")) {
            ENTxt.setEditable(true);
            if(VNTxt.getText().equals("")){
                message.setText("Vietnamese khong duoc de trong");
                return;
            }
            ListWord.add(new Word(++id, ENTxt.getText(), VNTxt.getText()));
            sortArray();
            message.setText("Da them thanh cong tu " + ENTxt.getText());
            ENTxt.setEnabled(true);
            Btn.setText("Tim Kiem");
        }
    }//GEN-LAST:event_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn;
    private javax.swing.JTextField ENTxt;
    private javax.swing.JTextField VNTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
